version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/build.sh
      runas: ec2-user
    - location: scripts/start_server.sh
      runas: ec2-user
